[GLOBAL]
pants_version = "2.18.0"
backend_packages = [
  "pants.backend.build_files.fmt.black",
  "pants.backend.docker",
  "pants.backend.experimental.terraform",
#  "pants.backend.experimental.terraform.lint.tfsec",
  "pants.backend.experimental.tools.yamllint",
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
]

[black]
install_from_resolve = "python-default"

[docker]
default_repository = "agoblet/polyglot_pants_example_{name}"
env_vars = ["DOCKER_CONFIG=%(homedir)s/.docker"]
build_args = ["GIT_COMMIT"]

[dockerfile-parser]
install_from_resolve = "python-default"

[docformatter]
install_from_resolve = "python-default"

[environments-preview.names]
docker_python = "//:docker_python"

[flake8]
install_from_resolve = "python-default"
requirements = ["flake8", "flake8-bugbear"]

[isort]
install_from_resolve = "python-default"

[mypy]
install_from_resolve = "python-default"
requirements = ["mypy","pandas-stubs"]

[pytest]
install_from_resolve = "python-default"

[python]
interpreter_constraints = ["==3.9.*"]
enable_resolves = true

[terraform-hcl2-parser]
install_from_resolve = "python-default"

[yamllint]
install_from_resolve = "python-default"
requirements = ["yamllint"]
